### ISSUE TITLE
[Changes/Improvements] Change the deployment target to 12.0

### ISSUE THREAD

**Issue by suraj-shetty** [dclelland/AlamofireEventSource#1]
I'm currently working on a project with 12.0 set as deployment target. 

I've a requirement for this pod. Could you update the pods?

**Comment by dclelland** [comment]
Sure, just publishing a v1.2.1 right now

**Comment by dclelland** [comment]
Or not, looks like I'm using a few 13.0-only APIs:

```
Validating podspec
 -> AlamofireEventSource (1.2.1)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Building targets in parallel
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    - ERROR | [iOS] xcodebuild:  AlamofireEventSource/Sources/EventSourceMessage.swift:58:37: error: 'scanUpToString' is only available in iOS 13.0 or newer
    - NOTE  | [iOS] xcodebuild:  AlamofireEventSource/Sources/EventSourceMessage.swift:58:37: note: add 'if #available' version check
    - NOTE  | xcodebuild:  AlamofireEventSource/Sources/EventSourceMessage.swift:55:18: note: add @available attribute to enclosing initializer
    - NOTE  | xcodebuild:  AlamofireEventSource/Sources/EventSourceMessage.swift:41:21: note: add @available attribute to enclosing struct
    - ERROR | [iOS] xcodebuild:  AlamofireEventSource/Sources/EventSourceMessage.swift:62:25: error: 'scanString' is only available in iOS 13.0 or newer
    - NOTE  | [iOS] xcodebuild:  AlamofireEventSource/Sources/EventSourceMessage.swift:62:25: note: add 'if #available' version check
    - ERROR | [iOS] xcodebuild:  AlamofireEventSource/Sources/EventSourceMessage.swift:64:39: error: 'scanUpToString' is only available in iOS 13.0 or newer
    - NOTE  | [iOS] xcodebuild:  AlamofireEventSource/Sources/EventSourceMessage.swift:64:39: note: add 'if #available' version check
    - NOTE  | xcodebuild:  note: Using codesigning identity override: 

[!] The spec did not pass validation, due to 4 errors.
```

I've not the time to sort this out atm, perhaps put together a PR if you like
